[build]
 functions = "netlify/functions"
  command = "npx @11ty/eleventy"
  publish = "_site"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200