# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: main
media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - label: 'Termine'
    name: 'termine'
    create: true
    summary: '{{appointments | size}} Termine: {{appointments | map: "appointment" | map: "message" | join(", ") | truncate(50)}}'
    files:
      - label: 'Appointments'
        name: 'appointments'
        format: 'json'
        file: 'src/_data/appointments.json'
        fields:
          - label: Appointment
            name: appointment
            widget: list
            summary: "{{time}} Uhr - {{date | date('DD.MM.YYYY')}} – {{message | capitalize}}"
            fields:
              - {
                  label: 'Date',
                  name: 'date',
                  widget: 'datetime',
                  format: 'YYYY-MM-DD',
                  date_format: 'YYYY-MM-DD',
                  time_format: false,
                }
              - { label: 'Time', name: 'time', widget: 'string' }
              - { label: 'Message', name: 'message', widget: 'string' }
